#!/bin/bash
# Generated by ant, March 6 2005
# Note that a Java runtime should be on the path.
# The current directory should be root of the Map Task data distribution
# (what you get when you unzip the public release).
# You must either unzip NXT in the same place or edit 
# this variable to contain the path to your  NXT installation.

NXT="."

export LD_LIBRARY_PATH=./fobs

export CLASSPATH=".:./lib:Data/configuration:$NXT:$NXT/lib:$NXT/lib/nxt.jar:$NXT/lib/jdom.jar:$NXT/lib/JMF/lib/jmf.jar:$NXT/fobs/fobs4jmf.jar:$NXT/lib/pnuts.jar:$NXT/lib/resolver.jar:$NXT/lib/xalan.jar:$NXT/lib/xercesImpl.jar:$NXT/lib/xml-apis.jar:$NXT/lib/jmanual.jar:$NXT/lib/jh.jar:$NXT/lib/helpset.jar:$NXT/lib/poi.jar:$NXT/lib/eclipseicons.jar:$NXT/lib/icons.jar:$NXT/lib/forms.jar:$NXT/lib/looks.jar:$NXT/lib/necoderHelp.jar:$NXT/lib/videolabelerHelp.jar:$NXT/lib/dacoderHelp.jar:$NXT/lib/testcoderHelp.jar:$NXT/lib/parlevink.jar"

java net.sourceforge.nite.nxt.GUI -corpus Data/maptask.xml

